<!DOCTYPE HTML>
<HTML>
<HEAD>
<TITLE>Assignment 5</TITLE>
<link rel="stylesheet" type="text/css" href="assign5.css">
</HEAD>
<BODY> 
<div id="third">
<h1>Calender</h1>
<?php
$month = $_GET["mName"];
$day = $_GET["mDay"];
$name = $_GET["nick"];

switch($month){
	
case "January":
case "March":
case "May":
case "July":
case "August":
case "October":
case "December":{
	switch($day){
		case "Monday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td>31<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
		case "Tuesday":echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td>31<td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	 case "Wednesday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td>31<td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;			   
	  case "Thursday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td>31<td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	    case "Friday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td>31<td>";
					   echo "</tr>";
					   break;
      case "Saturday": echo "<table>";
		               echo "<th colspan=7>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td>31<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
         case "Sunday":echo "<table>";
		               echo "<th colspan=7>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td>31<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	                   }					   
                    }
                    break;
case "April":
case "June":
case "September":
case "November":{
	switch($day){
		case "Monday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
		case "Tuesday":echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	 case "Wednesday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;			   
	  case "Thursday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	    case "Friday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
      case "Saturday": echo "<table>";
		               echo "<th colspan=7>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
         case "Sunday":echo "<table>";
		               echo "<th colspan=7>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td>30<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td>29<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	                   }					   
                    } 
                    break;
case "February":{
	switch($day){
		case "Monday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
		case "Tuesday":echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	 case "Wednesday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;			   
	  case "Thursday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	    case "Friday": echo "<table>";
		               echo "<th colspan=6>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
      case "Saturday": echo "<table>";
		               echo "<th colspan=7>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td> <td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td> <td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
         case "Sunday":echo "<table>";
		               echo "<th colspan=7>".$name."</th>";
					   echo "<tr>";
					   echo "<td>Monday<td>";
					   echo "<td> <td>";
					   echo "<td>2<td>";
					   echo "<td>9<td>";
					   echo "<td>16<td>";
					   echo "<td>23<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Tuesday<td>";
					   echo "<td> <td>";
					   echo "<td>3<td>";
					   echo "<td>10<td>";
					   echo "<td>17<td>";
					   echo "<td>24<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Wednesday<td>";
					   echo "<td> <td>";
					   echo "<td>4<td>";
					   echo "<td>11<td>";
					   echo "<td>18<td>";
					   echo "<td>25<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<tr>";
					   echo "<td>Thursday<td>";
					   echo "<td> <td>";
					   echo "<td>5<td>";
					   echo "<td>12<td>";
					   echo "<td>19<td>";
					   echo "<td>26<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Friday<td>";
					   echo "<td> <td>";
					   echo "<td>6<td>";
					   echo "<td>13<td>";
					   echo "<td>20<td>";
					   echo "<td>27<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Saturday<td>";
					   echo "<td> <td>";
					   echo "<td>7<td>";
					   echo "<td>14<td>";
					   echo "<td>21<td>";
					   echo "<td>28<td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   echo "<td>Sunday<td>";
					   echo "<td>1<td>";
					   echo "<td>8<td>";
					   echo "<td>15<td>";
					   echo "<td>22<td>";
					   echo "<td> <td>";
					   echo "<td> <td>";
					   echo "</tr>";
					   break;
	                   }					   
                    } 					
	}
?>
</div>
<style>
    #third{color: <?php echo $_GET["color"];?>;
    }
    </style>
</BODY>
</HTML>
